# Development Environment Configuration
# DevOps Showcase - Terraform Variables

# AWS Configuration
aws_region   = "eu-central-1"
environment  = "dev"
project_name = "devops-showcase"

# VPC Configuration
vpc_cidr = "10.0.0.0/16"

# Database Configuration
db_username = "dbadmin"
db_name     = "showcase_db"
# Note: DB password is auto-generated by Terraform and stored securely in AWS Parameter Store

# GitHub Repository for OIDC
# IMPORTANT: Update this with your actual GitHub repository
# Format: "repo:OWNER/REPOSITORY:*"
# Example: "repo:johndoe/devops_showcase:*"
github_repo_name = "repo:kdvalkov/ecs-distributed-platform-showcase:*"

# Instance Configuration (Free Tier Optimized)
ecs_instance_type = "t3.small"
db_instance_class = "db.t3.micro"
